PRAGMA foreign_keys = ON;

CREATE TABLE users(
    username VARCHAR(20) PRIMARY KEY,
    fullname VARCHAR(40) NOT NULL,
    email VARCHAR(20) NOT NULL,
    filename VARCHAR(64) NOT NULL,
    password VARCHAR(256) NOT NULL,
    created DATETIME
);

CREATE TABLE posts(
    postid INTEGER AUTO_INCREMENT,
    filename VARCHAR(64) NOT NULL,
    owner VARCHAR(20) NOT NULL,
    FOREIGN KEY (owner) REFERENCES users(username) ON DELETE CASCADE,
    created DATETIME
);

CREATE TABLE likes(
    likeid INTEGER PRIMARY KEY,
    owner VARCHAR(20) NOT NULL ON DELETE CASCADE,
    postid INTEGER NOT NULL ON DELETE CASCADE,
    created DATETIME 
    FOREIGN KEY (owner) REFERENCES users(username),
    FOREIGN KEY (postid) REFERENCES posts(postid)
);


CREATE TABLE FRIENDS (
    USER1_ID NOT NULL,
    USER2_ID NOT NULL,
    PRIMARY KEY (USER1_ID, USER2_ID),
    FOREIGN KEY (USER1_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (USER2_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    YEAR_OF_BIRTH INTEGER,
    MONTH_OF_BIRTH INTEGER,
    DAY_OF_BIRTH INTEGER,
    GENDER VARCHAR2(100)
);